version: '3'

services:
  procon31server:
    build: '.'
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/github.com/satackey/procon31server
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: ''
    command: sleep infinity

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - /mysql/entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=procon31
      - MYSQL_USER=procon31server
      - MYSQL_PASSWORD=${MYSQL_PROCON31SERVER_PASSWORD}
    expose:
      - '3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql:3306
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${PMA_PORT}:80
    volumes:
      - phpmyadmin-sessions:/sessions

volumes:
  phpmyadmin-sessions:
  mysql-data:
