version: '3'

services:
  procon30:
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ..:/go/src/github.com/satackey/procon31server
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: ''
    command: sleep infinity
