name: Test

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
