name: Test

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14'

    - uses: actions/checkout@v2
    
    - name: Test
      run: go test ./...

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
